# Generated by Django 3.1.4 on 2021-01-25 10:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Ειδικότητα')),
                ('lectic', models.CharField(max_length=100, verbose_name='Λεκτικό')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0, error_messages={'min_value': 'Η τιμή πρέπει να είναι μεγαλύτερη του 0.'}, help_text='Η τιμή πρέπει να είναι μεγαλύτερη του 0.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ώρες')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Χρονική σήμανση')),
                ('type', models.CharField(choices=[('Κενό', 'Κενό'), ('Πλεόνασμα', 'Πλεόνασμα')], default='Κενό', max_length=9, verbose_name='Κενό / Πλεόνασμα')),
                ('priority', models.BooleanField(default=False, verbose_name='Προτεραιότητα')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Παρατηρήσεις')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.specialty', verbose_name='Ειδικότητα')),
            ],
            options={
                'unique_together': {('specialty', 'owner')},
            },
        ),
    ]
