# Generated by Django 3.1.14 on 2022-10-24 09:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Ειδικότητα')),
                ('lectic', models.CharField(blank=True, max_length=100, verbose_name='Λεκτικό')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Λεκτικό Εκτύπωσης')),
                ('active', models.BooleanField(default=True, verbose_name='Διαθέσιμο προς χρήση')),
                ('ordering', models.SmallIntegerField(null=True, verbose_name='Σειρά')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0, error_messages={'min_value': 'Η τιμή πρέπει να είναι μεγαλύτερη του 0.'}, help_text='Η τιμή πρέπει να είναι μεγαλύτερη του 0.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ώρες')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Χρονική σήμανση')),
                ('type', models.CharField(choices=[('Κενό', 'Κενό'), ('Πλεόνασμα', 'Πλεόνασμα')], default='Κενό', max_length=9, verbose_name='Κενό / Πλεόνασμα')),
                ('description', models.TextField(blank=True, default='', help_text='Καταχωρίστε τυχόν παρατηρήσεις που μπορεί να έχετε για το συγεκριμένο κενό/πλεόνασμα', verbose_name='Παρατηρήσεις')),
                ('variant', models.CharField(choices=[('GENERAL_EDUCATION', 'Γενικής Αγωγής - μη Πανελλαδικώς Εξεταζόμενα Μαθήματα'), ('GENERAL_EDUCATION_WITH_EXAMS', 'Γενικής Αγωγής - Πανελλαδικώς Εξεταζόμενα Μαθήματα'), ('SPECIFIC_NEEDS_SMEAE', 'Ειδικής Αγωγής - ΣΜΕΑΕ'), ('SPECIFIC_NEEDS_INTEGRATION_CLASS', 'Ειδικής Αγωγής - Τμήμα Ένταξης'), ('SPECIFIC_NEEDS_INTEGRATION_CLASS_DEAF', 'Ειδικής Αγωγής - Τμήμα Ένταξης Κωφών'), ('SPECIFIC_NEEDS_INTEGRATION_CLASS_BLIND', 'Ειδικής Αγωγής - Τμήμα Ένταξης Τυφλών'), ('SPECIFIC_NEEDS_PARALLEL_SUPPORT', 'Ειδικής Αγωγής - Παράλληλης Στήριξης'), ('SPECIFIC_NEEDS_PARALLEL_SUPPORT_DEAF', 'Ειδικής Αγωγής - Παράλληλης Στήριξης Κωφών'), ('SPECIFIC_NEEDS_PARALLEL_SUPPORT_BLIND', 'Ειδικής Αγωγής - Παράλληλης Στήριξης Τυφλών'), ('VULNERABLE_GROUP', 'Ευπαθών Ομάδων'), ('BY_RESIGNATION', 'Από παραίτηση'), ('RECEPTION_CLASSES', 'Τάξεις Υποδοχής'), ('A_NEW_START', 'Μ.Ν.Α.Ε.'), ('MUSICAL_AKORTEON', 'Ακορντεόν'), ('MUSICAL_BIOLA', 'Βιόλα'), ('MUSICAL_BIOLI', 'Βιολί'), ('MUSICAL_BIOLI_TRADITIONAL', 'Βιολί (Παραδοσιακό)'), ('MUSICAL_BIOLOTSELO', 'Βιολοντσέλο'), ('MUSICAL_GAINDA', 'Γκάιντα'), ('MUSICAL_DIEYTH_ORXISTRAS', 'Διεύθυνση Ορχήστρας'), ('MUSICAL_DIEYTH_XORODIAS', 'Διεύθυνση Χορωδίας'), ('MUSICAL_ZOURNAS', 'Ζουρνάς'), ('MUSICAL_THEORHTIKA_BYZ_MOUSIKHS', 'Θεωρητικά Βυζαντινής Μουσικής'), ('MUSICAL_THEORHTIKA_EYR_MOUSIKHS', 'Θεωρητικά Ευρωπαϊκής Μουσικής'), ('MUSICAL_KANONAKI', 'Κανονάκι'), ('MUSICAL_KITHARA_HLEKTRIKI', 'Κιθάρα ηλεκτρική'), ('MUSICAL_KITHARA_KLASIKI', 'Κιθάρα κλασική'), ('MUSICAL_KLARINETO', 'Κλαρινέτο'), ('MUSICAL_KLARINO_PARADOSIAKO', 'Κλαρίνο (Παραδοσιακό)'), ('MUSICAL_KONTRAMPASO', 'Κοντραμπάσο'), ('MUSICAL_KORNO', 'Κόρνο'), ('MUSICAL_KROUSTA_EYR', 'Κρουστά Ευρωπαϊκά (Κλασικά - Σύγχρονα)'), ('MUSICAL_KROUSTA_PARADOSIAKA', 'Κρουστά παραδοσιακά'), ('MUSICAL_LAOUTO', 'Λαούτο'), ('MUSICAL_LYRA_DODEKANHSOU', 'Λύρα Δωδεκανήσου'), ('MUSICAL_LYRA_KRHTIKH', 'Λύρα Κρητική'), ('MUSICAL_LYRA_MAKEDONIAS', 'Λύρα Μακεδονίας'), ('MUSICAL_LYRA_POLITIKH', 'Λύρα Πολίτικη'), ('MUSICAL_LYRA_PONTIAKH', 'Λύρα Ποντιακή'), ('MUSICAL_MANTOLINO', 'Μαντολίνο'), ('MUSICAL_MOUSIKHS_TEXNLOGIAS', 'Μουσικής Τεχνολογίας (Εφαρμογές Η/Υ)'), ('MUSICAL_MPASO_HLEKTRIKO', 'Μπάσο ηλεκτρικό'), ('MUSICAL_MPOUZOUKI_TRIXORDO', 'Μπουζούκι (Τρίχορδο)'), ('MUSICAL_NEI_KABALI_PAR_AYLOI', 'Νέι-Καβάλι-Παραδοσιακοί Αυλοί'), ('MUSICAL_OMPOE', 'Όμποε'), ('MUSICAL_OUTI', 'Ούτι'), ('MUSICAL_PIANO', 'Πιάνο'), ('MUSICAL_SANTOURI', 'Σαντούρι'), ('MUSICAL_SAXOFONO', 'Σαξόφωνο (Άλτο - Βαρύτονο - Τενόρο)'), ('MUSICAL_TAMPOURA', 'Ταμπουράς'), ('MUSICAL_TOUMPA', 'Τούμπα'), ('MUSICAL_TROMPETA', 'Τρομπέτα'), ('MUSICAL_TROMPONI', 'Τρομπόνι'), ('MUSICAL_FAGOTO', 'Φαγκότο'), ('MUSICAL_FLAOUTO', 'Φλάουτο')], default='GENERAL_EDUCATION', help_text='Επιλέξετε το είδος του κενού', max_length=64, verbose_name='Τύπος Κενού / Πλεονάσματος')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='schools.school')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.specialty', verbose_name='Ειδικότητα')),
            ],
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('owner', 'specialty', 'variant'), name='unique_variant_entry'),
        ),
    ]
