# Generated by Django 3.1.4 on 2021-02-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210209_1528'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='unique owner_specialty_variant',
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('owner', 'specialty', 'variant'), name='owner_specialty_variant'),
        ),
    ]
