# Generated by Django 3.1.4 on 2021-02-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210209_2231'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='unique_entry',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='priority',
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('owner', 'specialty', 'variant'), name='unique_variant_entry'),
        ),
    ]
