# Generated by Django 3.1.4 on 2021-02-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210210_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Παρατηρήσεις'),
        ),
    ]
