# Generated by Django 3.1.4 on 2021-02-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210219_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'permissions': [('can_clear_all_entries', 'Can clear all entries'), ('can_view_all_entries', 'Can view all entries')]},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'permissions': [('can_view_all_specialities', 'Can view all specialties')]},
        ),
    ]
