# Generated by Django 3.1.4 on 2021-02-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210223_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={},
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Καταχωρήστε τυχόν παρατηρήσεις που μπορεί να έχετε για το συγεκριμένο κενό/πλεόνασμα', verbose_name='Παρατηρήσεις'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='variant',
            field=models.CharField(default='GENERAL_EDUCATION', help_text='Επιλέξετε το είδος του κενού', max_length=64, verbose_name='Τύπος Κενού / Πλεονάσματος'),
        ),
    ]
