# Generated by Django 3.1.8 on 2021-04-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20210409_1138'),
        ('main_app', '0013_auto_20210315_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='schools.school'),
        ),
    ]
