# Generated by Django 3.1.4 on 2021-09-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20210921_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Διαθέσιμο προς χρήση'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='label',
            field=models.CharField(max_length=100, null=True, verbose_name='Λεκτικό Εκτύπωσης'),
        ),
    ]
