# Generated by Django 3.1.4 on 2021-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210921_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Ειδικότητα'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Λεκτικό Εκτύπωσης'),
        ),
    ]
