version: '3.7'

services:
  web:
    build:
      context: .
    # volumes:
    #   - static_data:/vol/web
    networks:
      - frontend
      - backend
    ports:
      - 8888:80
    depends_on:
      - db
  db:
    image: mariadb:10.5
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    networks:
      - backend
    environment:
      MYSQL_DATABASE: 'vacancies-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - db_volume:/var/lib/mysql
  #nginx:
  #   build:
  #     context: ./_docker/nginx
  #   volumes:
  #     - static_data:/vol/static
  #   ports:
  #     - 8001:8080
  #   depends_on:
  #     - vacancies

volumes:
  static_data:
  db_volume:

networks:
  frontend:
  backend:
