version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker-images/web/Dockerfile
    volumes: 
      - type: volume
        source: static_volume
        target: /usr/share/nginx/html/static
        read_only: true
    networks:
      - frontend
      - backend
    expose:
      - "80"
    ports:
      - 8888:80
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: docker-images/app/Dockerfile
    # volumes:
    #   - static_data:/vol/web
    environment:
      MYSQL_DATABASE: 'vacancies_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'admin'
      SECRET_KEY: "some-secret-key"
      DJANGO_SETTINGS_MODULE: 'vacancies.settings.production'
    env_file: .env
    volumes: 
      - type: volume
        source: static_volume
        target: /app/static_files
    networks:
      - backend
    expose:
      - "80"
    depends_on:
      - db
  db:
    image: mariadb:10.5
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    networks:
      - backend
    environment:
      MYSQL_DATABASE: 'vacancies_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - type: volume
        source: db_volume
        target: /var/lib/mysql
  #nginx:
  #   build:
  #     context: ./_docker/nginx
  #   volumes:
  #     - static_data:/vol/static
  #   ports:
  #     - 8001:8080
  #   depends_on:
  #     - vacancies

volumes:
  static_volume:
  db_volume:

networks:
  frontend:
  backend:
