# Generated by Django 3.1.14 on 2022-10-24 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False, verbose_name='Επαληθεύτηκε από τη ΔΔΕ')),
                ('status', models.BooleanField(default=False, verbose_name='Έκανε επικαιροποίηση')),
                ('status_time', models.DateTimeField(default=None, null=True, verbose_name='Χρονική σήμανση επικαιροποίησης')),
                ('school', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_by', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
