# Generated by Django 3.2.25 on 2025-10-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Χρονική σήμανση επικαιροποίησης'),
        ),
    ]
