# Generated by Django 3.1.4 on 2021-02-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210219_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_clear_profiles_status', 'Can clear profile statuses'), ('can_check_profiles_status', 'Can check profile statutes')]},
        ),
    ]
