# Generated by Django 3.1.4 on 2021-03-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20210315_0822'),
        ('users', '0004_auto_20210228_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_by', to='schools.school'),
        ),
    ]
