# Generated by Django 3.1.4 on 2021-09-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status_time',
            field=models.DateTimeField(default=False, null=True, verbose_name='Χρονική σήμανση επικαιροποίησης'),
        ),
    ]
