# Generated by Django 3.1.12 on 2022-08-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210916_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Χρονική σήμανση επικαιροποίησης'),
        ),
    ]
