# Generated by Django 3.1.14 on 2022-10-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ομάδα')),
                ('ordering', models.PositiveSmallIntegerField(null=True, verbose_name='Σειρά')),
                ('neighboring_tag', models.CharField(db_index=True, max_length=5, null=True, verbose_name='Όμορη Όμαδα')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Σχολείου')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα Σχολείου')),
                ('myschool_name', models.CharField(max_length=100, null=True, verbose_name='Όνομα Σχολείου MySchool')),
                ('ministry_code', models.CharField(max_length=18, null=True, verbose_name='Κωδικός Υπουργείου')),
                ('principal', models.CharField(max_length=100, null=True, verbose_name='Διευθυντής Σχολείου')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Τηλέφωνο Σχολείου')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Διεύθυνση Σχολείου')),
                ('school_type', models.CharField(choices=[('GYMNASIO', 'Γυμνάσια'), ('GYMNASIO_LYKEIO', 'Γυμνάσιο Με Λυκειακές Τάξεις'), ('LYKEIO', 'Λύκεια'), ('EPAL', 'Επαγγελματικά Λύκεια'), ('EEEEK', 'Ειδικής Επαγγελματικής Εκπαίδευσης και Κατάρτισης')], default='LYKEIO', help_text='Επιλέξετε τον τύπο της σχολική μονάδας (Γυμνάσιο/Λύκειο/...)', max_length=64, verbose_name='Έιδος Σχολείου')),
                ('school_variant', models.CharField(choices=[('HMERISIO_GYM', 'Ημερήσιο Γυμνάσιο'), ('HMERISIO_LYK', 'Ημερήσιο Γενικό Λύκειο'), ('EIDIKIS_AGOGIS_GYM', 'Γυμνάσιο Ειδικής Αγωγής'), ('ΕΕΕΕΚ', 'ΕΕΕΕΚ'), ('ENIAIO_EIDIKO_GYM_LYK', 'Ενιαίο Ειδικό Επαγγελματικό Γυμνάσιο - Λύκειο'), ('ESPERINO_LYK', 'Εσπερινό Γενικό Λύκειο'), ('ESPERINO_GYM', 'Εσπερινό Γυμνάσιο'), ('ESPERINO_GYM_LYK_TAKSEIS', 'Εσπερινό Γυμνάσιο με Λυκειακές Τάξεις'), ('ESPERINO_EPAL', 'Εσπερινό ΕΠΑΛ'), ('HMERISIO_EPAL', 'Ημερήσιο ΕΠΑΛ'), ('KALITEXNIKO_GYM_LYK_TAKSEIS', 'Καλλιτεχνικό Γυμνάσιο με Λυκειακές Τάξεις'), ('MOYSIKO_GYM_LYK_TAKSEIS', 'Μουσικό Γυμνάσιο με Μουσικές Λυκειακές Τάξεις'), ('PROTYPO_GYM', 'Πρότυπο Γυμνάσιο'), ('PROTYPO_LYK', 'Πρότυπο Λύκειο')], default='HMERISIO_LYK', help_text='Επιλέξετε την κατηγορία της σχολικής μονάδας', max_length=58, verbose_name='Κατηγορία')),
                ('school_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.schoolgroup', verbose_name='Σχολική Ομάδα')),
                ('sibling_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='Συστεγαζόμενο Σχολείο')),
            ],
        ),
    ]
