# Generated by Django 3.2.25 on 2024-10-23 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Διεύθυνση Σχολείου'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ministry_code',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Κωδικός Υπουργείου'),
        ),
        migrations.AlterField(
            model_name='school',
            name='myschool_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα Σχολείου MySchool'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Τηλέφωνο Σχολείου'),
        ),
        migrations.AlterField(
            model_name='school',
            name='principal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Διευθυντής Σχολείου'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sibling_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='Συστεγαζόμενο Σχολείο'),
        ),
    ]
