# Generated by Django 3.1.4 on 2021-02-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20210223_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
    ]
