# Generated by Django 3.2.25 on 2025-10-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20241023_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClassesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_grade_classes', models.PositiveSmallIntegerField(default=0, help_text="Συνολικά Τμήματα Α' Τάξης")),
                ('b_grade_classes', models.PositiveSmallIntegerField(default=0, help_text="Συνολικά Τμήματα Β' Τάξης")),
                ('c_grade_classes', models.PositiveSmallIntegerField(default=0, help_text="Συνολικά Τμήματα Γ' Τάξης")),
                ('a_grade_classes_over_21', models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Α' Τάξης με πάνω απο 21 μαθητές")),
                ('b_grade_classes_over_21', models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Β' Τάξης με πάνω απο 21 μαθητές")),
                ('c_grade_classes_over_21', models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Γ' Τάξης με πάνω απο 21 μαθητές")),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='Σχολείο')),
            ],
        ),
    ]
