# Generated by Django 3.1.4 on 2021-03-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20210228_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_timetable',
            field=models.CharField(choices=[('ESPERINO', 'Εσπερινό'), ('HMERISIO', 'Ημερήσιο')], default='HMERISIO', help_text='Επιλέξετε τον το ωράριο λειτουργίας της σχολικής μονάδας', max_length=16, verbose_name='Ωράριο Λειτουργίας'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('GYMNASIO', 'Γυμνάσιο'), ('GYMNASIO_LYKEIO', 'Γυμνάσιο Με Λυκειακές Τάξεις'), ('LYKEIO', 'Λύκειο'), ('EPAL', 'ΕΠΑΛ')], default='LYKEIO', help_text='Επιλέξετε τον τύπο της σχολική μονάδας (Γυμνάσιο/Λύκειο/...)', max_length=16, verbose_name='Έιδος Σχολείου'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_variant',
            field=models.CharField(choices=[('GENERAL', 'Γενικής Παιδείας'), ('MUSIC', 'Μουσικό'), ('ART', 'Καλλιτεχνικό'), ('PEIRAMATIKO', 'Πειραματικό'), ('EIDIKO', 'Ειδικό')], default='GENERAL', help_text='Επιλέξετε την κατηγορία της σχολικής μονάδας', max_length=16, verbose_name='Κατηγορία'),
        ),
    ]
