# Generated by Django 3.2.25 on 2025-10-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schoolclassesinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclassesinfo',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classes_info', to='schools.school', verbose_name='Σχολείο'),
        ),
    ]
