# Generated by Django 3.2.25 on 2025-10-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_schoolclassesinfo_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='a_grade_classes_french',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Γαλλικών Α' Τάξης"),
        ),
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='a_grade_classes_german',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Γερμανικών Α' Τάξης"),
        ),
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='b_grace_classes_anthropistikon',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Ανθρωπιστικών Β' Τάξης"),
        ),
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='b_grace_classes_prosanatolismou',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Προσανατολισμού Β' Τάξης"),
        ),
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='b_grade_classes_french',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Γαλλικών Β' Τάξης"),
        ),
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='b_grade_classes_german',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Γερμανικών Β' Τάξης"),
        ),
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='c_grade_classes_anthropistikon',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Ανθρωπιστικών Γ' Τάξης"),
        ),
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='c_grade_classes_french',
            field=models.PositiveSmallIntegerField(default=0, help_text="Συνολικά Τμήματα Γενικής Γ' Τάξης"),
        ),
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='c_grade_classes_german',
            field=models.PositiveSmallIntegerField(default=0, help_text="Συνολικά Τμήματα Γενικής Γ' Τάξης"),
        ),
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='c_grade_classes_pliroforikis',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Πληροφορικής & Υγείας Γ' Τάξης"),
        ),
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='c_grade_classes_prosanatolismou',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Προσανατολισμού Γ' Τάξης"),
        ),
        migrations.AddField(
            model_name='schoolclassesinfo',
            name='c_grade_classes_thetikon',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Θετικών Επιστημών Γ' Τάξης"),
        ),
        migrations.AlterField(
            model_name='schoolclassesinfo',
            name='a_grade_classes',
            field=models.PositiveSmallIntegerField(default=0, help_text="Συνολικά Τμήματα Γενικής Α' Τάξης"),
        ),
        migrations.AlterField(
            model_name='schoolclassesinfo',
            name='a_grade_classes_over_21',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Γενικής Α' Τάξης με πάνω απο 21 μαθητές"),
        ),
        migrations.AlterField(
            model_name='schoolclassesinfo',
            name='b_grade_classes',
            field=models.PositiveSmallIntegerField(default=0, help_text="Συνολικά Τμήματα Γενικής Β' Τάξης"),
        ),
        migrations.AlterField(
            model_name='schoolclassesinfo',
            name='b_grade_classes_over_21',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Γενικής Β' Τάξης με πάνω απο 21 μαθητές"),
        ),
        migrations.AlterField(
            model_name='schoolclassesinfo',
            name='c_grade_classes',
            field=models.PositiveSmallIntegerField(default=0, help_text="Συνολικά Τμήματα Γενικής Γ' Τάξης"),
        ),
        migrations.AlterField(
            model_name='schoolclassesinfo',
            name='c_grade_classes_over_21',
            field=models.PositiveSmallIntegerField(default=0, help_text="Τμήματα Γενικής Γ' Τάξης με πάνω απο 21 μαθητές"),
        ),
    ]
