# Generated by Django 3.1.4 on 2021-04-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20210315_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='connected_to_user',
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Διεύθυνση Σχολείου'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Όνομα Σχολείου'),
        ),
    ]
