# Generated by Django 3.2.25 on 2025-10-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20251008_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclassesinfo',
            name='a_grade_classes',
            field=models.PositiveSmallIntegerField(default=0, help_text="fsdjkfklsdjdfsjkl Συνολικά Τμήματα Γενικής Α' Τάξης", verbose_name='Σχολείο'),
        ),
    ]
