# Generated by Django 3.1.4 on 2021-09-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20210901_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgroup',
            name='ordering',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Σειρά'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.schoolgroup', verbose_name='Σχολική Ομάδα'),
        ),
    ]
