# Generated by Django 3.1.12 on 2022-05-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20210916_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ministry_code',
            field=models.CharField(max_length=18, null=True, verbose_name='Κωδικός Υπουργείου'),
        ),
    ]
