# Generated by Django 3.1.12 on 2022-05-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_school_ministry_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='siblings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
