# Generated by Django 3.1.12 on 2022-05-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_siblings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='siblings',
            new_name='sibling_school',
        ),
    ]
