# Generated by Django 3.1.12 on 2022-05-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20220502_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='neighboring_groups',
            field=models.CharField(max_length=32, null=True, verbose_name='Όμορες Ομάδες'),
        ),
    ]
