# Generated by Django 3.1.12 on 2022-05-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20220503_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgroup',
            name='neighboring_tag',
            field=models.CharField(db_index=True, max_length=5, null=True, verbose_name='Όμορη Όμαδα'),
        ),
    ]
