# Generated by Django 3.1.12 on 2022-05-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_schoolgroup_neighboring_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_timetable',
        ),
    ]
