# Generated by Django 3.1.12 on 2022-05-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_remove_school_school_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='neighboring_groups',
        ),
    ]
