# Generated by Django 3.1.12 on 2022-05-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_remove_school_neighboring_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_variant',
            field=models.CharField(choices=[('HMERISIO_GYM', 'Ημερήσιο Γυμνάσιο'), ('HMERISIO_LYK', 'Ημερήσιο Γενικό Λύκειο'), ('EIDIKIS_AGOGIS_GYM', 'Γυμνάσιο Ειδικής Αγωγής'), ('ΕΕΕΕΚ', 'ΕΕΕΕΚ'), ('ENIAIO_EIDIKO_GYM_LYK', 'Ενιαίο Ειδικό Επαγγελματικό Γυμνάσιο - Λύκειο'), ('ESPERINO_LYK', 'Εσπερινό Γενικό Λύκειο'), ('ESPERINO_GYM', 'Εσπερινό Γυμνάσιο'), ('ESPERINO_GYM_LYK_TAKSEIS', 'Εσπερινό Γυμνάσιο με Λυκειακές Τάξεις'), ('ESPERINO_EPAL', 'Εσπερινό ΕΠΑΛ'), ('HMERISIO_EPAL', 'Ημερήσιο ΕΠΑΛ'), ('KALITEXNIKO_GYM_LYK_TAKSEIS', 'Καλλιτεχνικό Γυμνάσιο με Λυκειακές Τάξεις'), ('MOYSIKO_GYM_LYK_TAKSEIS', 'Μουσικό Γυμνάσιο με Μουσικές Λυκειακές Τάξεις'), ('PROTYPO_GYM', 'Πρότυπο Γυμνάσιο'), ('PROTYPO_LYK', 'Πρότυπο Λύκειο')], default='HMERISIO_LYK', help_text='Επιλέξετε την κατηγορία της σχολικής μονάδας', max_length=58, verbose_name='Κατηγορία'),
        ),
    ]
