# Generated by Django 3.1.4 on 2021-01-25 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Χρονική σήμανση')),
                ('type', models.CharField(choices=[('Κενό', 'Κενό'), ('Πλεόνασμα', 'Πλεόνασμα')], default='Κενό', max_length=9, verbose_name='Κενό / Πλεόνασμα')),
                ('priority', models.BooleanField(default=False, verbose_name='Προτεραιότητα')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Παρατηρήσεις')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.specialty', verbose_name='Ειδικότητα')),
            ],
        ),
    ]
