# Generated by Django 3.1.4 on 2021-02-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_remove_historyentry_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyentry',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Παρατηρήσεις'),
        ),
    ]
