# Generated by Django 3.1.4 on 2021-02-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20210219_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyentry',
            options={'permissions': [('can_clear_all_history_entries', 'Can clear all history entries')]},
        ),
    ]
