# Generated by Django 3.1.4 on 2021-02-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20210219_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyentry',
            options={},
        ),
    ]
