# Generated by Django 3.1.4 on 2021-08-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_auto_20210315_0805'),
        ('history', '0005_auto_20210827_1107'),
    ]

    operations = [
    ]
