# Generated by Django 3.1.4 on 2021-08-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_merge_20210831_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyentry',
            name='variant',
            field=models.CharField(choices=[('GENERAL_EDUCATION', 'Γενικής Παιδείας - μη Πανελλαδικώς Εξεταζόμενα Μαθήματα'), ('GENERAL_EDUCATION_WITH_EXAMS', 'Γενικής Παιδείας - Πανελλαδικώς Εξεταζόμενα Μαθήματα'), ('SPECIFIC_NEEDS_SMEAE', 'Ειδικής Αγωγής - ΣΜΕΑΕ'), ('SPECIFIC_NEEDS_INTEGRATION_CLASS', 'Ειδικής Αγωγής - Τμήμα Ένταξης'), ('SPECIFIC_NEEDS_INTEGRATION_CLASS_DEAF', 'Ειδικής Αγωγής - Τμήμα Ένταξης Κωφών'), ('SPECIFIC_NEEDS_INTEGRATION_CLASS_BLIND', 'Ειδικής Αγωγής - Τμήμα Ένταξης Τυφλών'), ('SPECIFIC_NEEDS_PARALLEL_SUPPORT', 'Ειδικής Αγωγής - Παράλληλης Στήριξης'), ('SPECIFIC_NEEDS_PARALLEL_SUPPORT_DEAF', 'Ειδικής Αγωγής - Παράλληλης Στήριξης Κωφών'), ('SPECIFIC_NEEDS_PARALLEL_SUPPORT_BLIND', 'Ειδικής Αγωγής - Παράλληλης Στήριξης Τυφλών'), ('VULNERABLE_GROUP', 'Ευπαθών Ομάδων'), ('BY_RESIGNATION', 'Από παραίτηση'), ('RECEPTION_CLASSES', 'Τάξεις Υποδοχής'), ('A_NEW_START', 'Μ.Ν.Α.Ε.'), ('MUSICAL_AKORTEON', 'Ακορντεόν'), ('MUSICAL_BIOLA', 'Βιόλα'), ('MUSICAL_BIOLI', 'Βιολί'), ('MUSICAL_BIOLI_TRADITIONAL', 'Βιολί (Παραδοσιακό)'), ('MUSICAL_BIOLOTSELO', 'Βιολοντσέλο'), ('MUSICAL_GAINDA', 'Γκάιντα'), ('MUSICAL_DIEYTH_ORXISTRAS', 'Διεύθυνση Ορχήστρας'), ('MUSICAL_DIEYTH_XORODIAS', 'Διεύθυνση Χορωδίας'), ('MUSICAL_ZOURNAS', 'Ζουρνάς'), ('MUSICAL_THEORHTIKA_BYZ_MOUSIKHS', 'Θεωρητικά Βυζαντινής Μουσικής'), ('MUSICAL_THEORHTIKA_EYR_MOUSIKHS', 'Θεωρητικά Ευρωπαϊκής Μουσικής'), ('MUSICAL_KANONAKI', 'Κανονάκι'), ('MUSICAL_KITHARA_HLEKTRIKI', 'Κιθάρα ηλεκτρική'), ('MUSICAL_KITHARA_KLASIKI', 'Κιθάρα κλασική'), ('MUSICAL_KLARINETO', 'Κλαρινέτο'), ('MUSICAL_KLARINO_PARADOSIAKO', 'Κλαρίνο (Παραδοσιακό)'), ('MUSICAL_KONTRAMPASO', 'Κοντραμπάσο'), ('MUSICAL_KORNO', 'Κόρνο'), ('MUSICAL_KROUSTA_EYR', 'Κρουστά Ευρωπαϊκά (Κλασικά - Σύγχρονα)'), ('MUSICAL_KROUSTA_PARADOSIAKA', 'Κρουστά παραδοσιακά'), ('MUSICAL_LAOUTO', 'Λαούτο'), ('MUSICAL_LYRA_DODEKANHSOU', 'Λύρα Δωδεκανήσου'), ('MUSICAL_LYRA_KRHTIKH', 'Λύρα Κρητική'), ('MUSICAL_LYRA_MAKEDONIAS', 'Λύρα Μακεδονίας'), ('MUSICAL_LYRA_POLITIKH', 'Λύρα Πολίτικη'), ('MUSICAL_LYRA_PONTIAKH', 'Λύρα Ποντιακή'), ('MUSICAL_MANTOLINO', 'Μαντολίνο'), ('MUSICAL_MOUSIKHS_TEXNLOGIAS', 'Μουσικής Τεχνολογίας (Εφαρμογές Η/Υ)'), ('MUSICAL_MPASO_HLEKTRIKO', 'Μπάσο ηλεκτρικό'), ('MUSICAL_MPOUZOUKI_TRIXORDO', 'Μπουζούκι (Τρίχορδο)'), ('MUSICAL_NEI_KABALI_PAR_AYLOI', 'Νέι-Καβάλι-Παραδοσιακοί Αυλοί'), ('MUSICAL_OMPOE', 'Όμποε'), ('MUSICAL_OUTI', 'Ούτι'), ('MUSICAL_PIANO', 'Πιάνο'), ('MUSICAL_SANTOURI', 'Σαντούρι'), ('MUSICAL_SAXOFONO', 'Σαξόφωνο (Άλτο - Βαρύτονο - Τενόρο)'), ('MUSICAL_TAMPOURA', 'Ταμπουράς'), ('MUSICAL_TOUMPA', 'Τούμπα'), ('MUSICAL_TROMPETA', 'Τρομπέτα'), ('MUSICAL_TROMPONI', 'Τρομπόνι'), ('MUSICAL_FAGOTO', 'Φαγκότο'), ('MUSICAL_FLAOUTO', 'Φλάουτο')], default='GENERAL_EDUCATION', help_text='Επιλέξετε το είδος του κενού', max_length=64, verbose_name='Τύπος Κενού / Πλεονάσματος'),
        ),
    ]
