# Generated by Django 3.1.12 on 2022-01-13 15:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0008_auto_20210916_1208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0020_auto_20211004_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, default='', max_length=32, verbose_name='Όνομα Εκπ/ου')),
                ('teacher_surname', models.CharField(blank=True, default='', max_length=32, verbose_name='Επώνυμο Εκπ/ου')),
                ('teacher_registry', models.IntegerField(blank=True, default=None, null=True, verbose_name='Α.Μ.')),
                ('hours', models.IntegerField(default=0, error_messages={'min_value': 'Η τιμή πρέπει να είναι μεγαλύτερη του 0.'}, help_text='Η τιμή πρέπει να είναι μεγαλύτερη του 0.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ώρες')),
                ('illness_started', models.DateField(auto_now=True, verbose_name='Ημ/νια Νόσησης')),
                ('illness_end_estimation', models.DateField(blank=True, null=True, verbose_name='Ημ/νια Πιθανής Επιστροφής')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.TextField(blank=True, default='', help_text='Καταχωρίστε τυχόν παρατηρήσεις που μπορεί να έχετε για το συγεκριμένο προσωρινό COVID-19 κενό', verbose_name='Παρατηρήσεις')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covid19_entries', to='schools.school')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.specialty', verbose_name='Ειδικότητα')),
            ],
        ),
        migrations.CreateModel(
            name='Covid19EntryEventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_datetime', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('INSERT', 'Καταχώρηση Εγγραφής'), ('UPDATE', 'Τροποποίηση Εγγραφής'), ('DELETE', 'Διαγραφή Εγγραφής')], default='INSERT', max_length=15)),
                ('event_description', models.TextField(blank=True, default='')),
                ('covid_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid19.covid19entry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='covid19entryeventhistory',
            index=models.Index(fields=['covid_entry'], name='covid19_cov_covid_e_2d6a36_idx'),
        ),
        migrations.AddIndex(
            model_name='covid19entryeventhistory',
            index=models.Index(fields=['event_datetime'], name='covid19_cov_event_d_d60833_idx'),
        ),
        migrations.AddIndex(
            model_name='covid19entry',
            index=models.Index(fields=['school', 'specialty'], name='covid19_cov_school__c8cbcf_idx'),
        ),
        migrations.AddIndex(
            model_name='covid19entry',
            index=models.Index(fields=['created_on'], name='covid19_cov_created_1d764a_idx'),
        ),
    ]
