# Generated by Django 3.1.12 on 2022-01-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0002_auto_20220114_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19entry',
            name='illness_started',
            field=models.DateField(verbose_name='Ημ/νια Νόσησης'),
        ),
    ]
